// File: DeleteBillController.js
// Author: Priyank Gosalia <priyank.gosalia@gmail.com>
// Created on: 5th January 2016

(function () {
    'use strict';
    angular.module('billApp').controller('DeleteBillController', DeleteBillController);
    DeleteBillController.$inject = ['$location', '$scope', 'BillService', 'AuthenticationService','$window', '$timeout'];

    function DeleteBillController($location, $scope, BillService, AuthenticationService, $window, $timeout) {
	   	var cm = {};
	   	cm.AuthenticationService = AuthenticationService;
	   	cm.currentUser = AuthenticationService.GetUsername();
	   	cm.currentUserFirstName = AuthenticationService.GetUserFirstName();
	   	cm.getBillInfo = getBillInfo;
	   	cm.deleteBill = deleteBill;
	   	cm.dataLoading = false;
	   	cm.deleteOption="this";

	    angular.element(document).ready(function () {
	    	getBillInfo($scope.billId);
	    });

        return cm;
        
        function deleteBill() {
        	if (confirm("Are you sure you want to delete this Bill ?")) {
        		var billId = $('#billId').val();
            	var deleteOption = cm.deleteOption;
            	var deleteRecur = false;
            	if (deleteOption == "thisandrecur") {
            		deleteRecur = true;
            	}
            	cm.dataLoading = true;
            	BillService.deleteBill(billId,deleteRecur,function(response){
            		console.log(response);
            		var result = response.result;
            		cm.dataLoading = false;
            		if (response.result == false) {
            			cm.deleteBillFailure = true;
            			cm.deleteBillFailureMessage = response.message;
            		} else {
            			cm.deleteBillFailure = false;
            			cm.deleteBillFailureMessage = null;
            			cm.deleteBillSuccess = true;
            			cm.deleteBillSuccessMessage = response.message;
            			$scope.closeThisDialog('v');
            			alert("Bill deleted successfully");
            		}
            	});
        	}
        }

        function getBillInfo(billId) {
        	cm.dataLoading = true;
        	BillService.getBillInfo(billId,function (response) {
                if (response) {
                    $scope.billInfo = response.data;
                    $timeout(function(){
                    	var d = new Date($scope.billInfo.dueDate),
                        month = '' + (d.getMonth() + 1),
                        day = '' + d.getDate(),
                        year = d.getFullYear();
	                    if (month.length < 2) month = '0' + month;
	                    if (day.length < 2) day = '0' + day;
	                    $scope.billInfo.dueDate=[day, month, year].join('/');
	                    if ($scope.billInfo.recurring == true) {
	                    	$scope.recurringText = "Recurring Bill";
	                    } else {
	                    	$scope.recurringText = "Non-Recurring Bill";
	                    }
	                    if ($scope.billInfo.status == "Paid") {
	                    	$scope.paid = true;
	                    } else {
	                    	$scope.paid = false;
	                    }
	                    if ($scope.billInfo.autoGenerated == true) {
	                    	$scope.autoGen = true;
	                    } else {
	                    	$scope.autoGen = false;
	                    }
        	    	},10);
                } else {
                	$scope.billInfo = null;
                }
                cm.dataLoading = false;
                return $scope.billInfo;
            });
        }
	}
})();